LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: ruby19

Layout/SpaceBeforeFirstArg:
  Enabled: false

Metrics/AbcSize:
  Max: 26

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Naming/FileName:
  Enabled: false

AllCops:
  Exclude:
    - '**/*.gemspec'
    - 'spec/**/*'
    - '**/Rakefile'
